# ONBUILD instructions in base-image/Dockerfile are used to
# perform certain actions based on the presence of specific
# files (such as conda-linux-64.lock, start) in this repo.
# Refer to the base-image/Dockerfile for documentation.
ARG SSEC_BASE_IMAGE_TAG=latest
FROM ghcr.io/uw-ssec/base-image:${SSEC_BASE_IMAGE_TAG}